#!/bin/bash

# Automated deployment and configuration script for ICP canisters
# This script:
# 1. Deploys all canisters
# 2. Gets canister IDs
# 3. Configures bridge_orchestrator with IDs
# 4. Generates TypeScript declarations
# 5. Updates Mobile app .env file
# 6. Validates configuration

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ICP_BRIDGE_DIR="$SCRIPT_DIR"
MOBILE_DIR="$PROJECT_ROOT/Mobile"

echo "======================================"
echo "ICP Canister Deployment & Configuration"
echo "======================================"
echo ""

# Use NO_COLOR to avoid dfx panic
export NO_COLOR=1

# Change to ICP bridge directory
cd "$ICP_BRIDGE_DIR"

# Step 1: Check if dfx is running
echo -e "${BLUE}Step 1: Checking dfx replica...${NC}"
if ! NO_COLOR=1 dfx ping local &> /dev/null; then
    echo -e "${YELLOW}Starting dfx local replica with network access...${NC}"
    echo -e "${YELLOW}Note: Bitcoin integration canister errors are expected and harmless in local development${NC}"
    echo -e "${YELLOW}The system canister will try to connect to Bitcoin regtest network, which is normal.${NC}"
    NO_COLOR=1 dfx start --host 0.0.0.0:4943 --background --clean 2>&1 | grep -v "Error fetching blocks\|ConnectionBroken" || true
    echo "Waiting for replica to start..."
    sleep 8
    echo -e "${GREEN}✓ dfx replica started${NC}"
else
    echo -e "${GREEN}✓ dfx replica is already running${NC}"
fi
echo ""

# Step 2: Build canisters
echo -e "${BLUE}Step 2: Building canisters...${NC}"
NO_COLOR=1 dfx build btc_handler
NO_COLOR=1 dfx build solana_canister
NO_COLOR=1 dfx build bridge_orchestrator
echo -e "${GREEN}✓ Build complete${NC}"
echo ""

# Step 3: Deploy canisters
echo -e "${BLUE}Step 3: Deploying canisters...${NC}"
NO_COLOR=1 dfx deploy btc_handler
NO_COLOR=1 dfx deploy solana_canister
NO_COLOR=1 dfx deploy bridge_orchestrator
echo -e "${GREEN}✓ Deployment complete${NC}"
echo ""

# Step 4: Get canister IDs
echo -e "${BLUE}Step 4: Retrieving canister IDs...${NC}"
BTC_ID=$(NO_COLOR=1 dfx canister id btc_handler)
SOL_ID=$(NO_COLOR=1 dfx canister id solana_canister)
BRIDGE_ID=$(NO_COLOR=1 dfx canister id bridge_orchestrator)

echo -e "${GREEN}✓ Canister IDs retrieved:${NC}"
echo "  BTC Handler:        $BTC_ID"
echo "  Solana Canister:    $SOL_ID"
echo "  Bridge Orchestrator: $BRIDGE_ID"
echo ""

# Step 5: Configure bridge_orchestrator
echo -e "${BLUE}Step 5: Configuring bridge_orchestrator...${NC}"
CONFIG_RESULT=$(NO_COLOR=1 dfx canister call bridge_orchestrator set_canister_ids "(\"$BTC_ID\", \"$SOL_ID\")" 2>&1)
if echo "$CONFIG_RESULT" | grep -q "error\|Error\|failed\|Failed"; then
    echo -e "${RED}✗ Configuration failed:${NC}"
    echo "$CONFIG_RESULT"
    exit 1
else
    echo -e "${GREEN}✓ Bridge orchestrator configured${NC}"
fi
echo ""

# Step 6: Generate TypeScript declarations
echo -e "${BLUE}Step 6: Generating TypeScript declarations...${NC}"
NO_COLOR=1 dfx generate
echo -e "${GREEN}✓ Declarations generated${NC}"
echo ""

# Step 7: Detect WSL IP (if running in WSL)
echo -e "${BLUE}Step 7: Detecting WSL IP...${NC}"
WSL_IP=""
if command -v ip &> /dev/null; then
    # Try to get WSL IP
    WSL_IP=$(ip addr show eth0 2>/dev/null | grep "inet " | awk '{print $2}' | cut -d/ -f1 || echo "")
fi

if [ -z "$WSL_IP" ]; then
    # Try alternative method
    WSL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")
fi

if [ -n "$WSL_IP" ]; then
    echo -e "${GREEN}✓ WSL IP detected: $WSL_IP${NC}"
else
    echo -e "${YELLOW}⚠ WSL IP not detected. You may need to set EXPO_PUBLIC_WSL_IP manually${NC}"
fi
echo ""

# Step 8: Update Mobile app .env file
echo -e "${BLUE}Step 8: Updating Mobile app configuration...${NC}"
MOBILE_ENV_FILE="$MOBILE_DIR/.env"

# Create .env file if it doesn't exist
if [ ! -f "$MOBILE_ENV_FILE" ]; then
    touch "$MOBILE_ENV_FILE"
    echo "# Auto-generated by deploy-and-configure.sh" >> "$MOBILE_ENV_FILE"
    echo "# Generated: $(date)" >> "$MOBILE_ENV_FILE"
    echo "" >> "$MOBILE_ENV_FILE"
fi

# Update or add canister IDs
update_env_var() {
    local key=$1
    local value=$2
    local file=$3
    
    if grep -q "^${key}=" "$file" 2>/dev/null; then
        # Update existing value
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
        else
            sed -i "s|^${key}=.*|${key}=${value}|" "$file"
        fi
    else
        # Add new value
        echo "${key}=${value}" >> "$file"
    fi
}

update_env_var "EXPO_PUBLIC_BTC_HANDLER_CANISTER_ID" "$BTC_ID" "$MOBILE_ENV_FILE"
update_env_var "EXPO_PUBLIC_BRIDGE_ORCHESTRATOR_CANISTER_ID" "$BRIDGE_ID" "$MOBILE_ENV_FILE"
update_env_var "EXPO_PUBLIC_SOLANA_CANISTER_ID" "$SOL_ID" "$MOBILE_ENV_FILE"

if [ -n "$WSL_IP" ]; then
    update_env_var "EXPO_PUBLIC_WSL_IP" "$WSL_IP" "$MOBILE_ENV_FILE"
fi

update_env_var "EXPO_PUBLIC_ICP_PORT" "4943" "$MOBILE_ENV_FILE"

echo -e "${GREEN}✓ Mobile app .env updated${NC}"
echo ""

# Step 9: Copy declarations to Mobile app
echo -e "${BLUE}Step 9: Copying declarations to Mobile app...${NC}"
if [ -d "$MOBILE_DIR/declarations" ]; then
    cp -r "$ICP_BRIDGE_DIR/src/declarations/"* "$MOBILE_DIR/declarations/"
    echo -e "${GREEN}✓ Declarations copied${NC}"
else
    echo -e "${YELLOW}⚠ Mobile/declarations directory not found. Skipping...${NC}"
fi
echo ""

# Step 10: Validate configuration
echo -e "${BLUE}Step 10: Validating configuration...${NC}"
VALIDATION_ERRORS=0

# Check if canister IDs are set
if [ -z "$BTC_ID" ] || [ -z "$SOL_ID" ] || [ -z "$BRIDGE_ID" ]; then
    echo -e "${RED}✗ Missing canister IDs${NC}"
    VALIDATION_ERRORS=$((VALIDATION_ERRORS + 1))
fi

# Test canister calls
echo "  Testing BTC handler canister..."
if NO_COLOR=1 dfx canister call btc_handler get_canister_stats 2>&1 | grep -q "error\|Error"; then
    echo -e "${YELLOW}  ⚠ BTC handler test failed (may be expected)${NC}"
else
    echo -e "${GREEN}  ✓ BTC handler accessible${NC}"
fi

echo "  Testing bridge orchestrator..."
if NO_COLOR=1 dfx canister call bridge_orchestrator get_bridge_stats 2>&1 | grep -q "error\|Error"; then
    echo -e "${YELLOW}  ⚠ Bridge orchestrator test failed (may be expected)${NC}"
else
    echo -e "${GREEN}  ✓ Bridge orchestrator accessible${NC}"
fi

echo ""

# Summary
echo "======================================"
echo -e "${GREEN}Deployment & Configuration Complete!${NC}"
echo "======================================"
echo ""
echo "Canister IDs:"
echo "  BTC Handler:        $BTC_ID"
echo "  Solana Canister:    $SOL_ID"
echo "  Bridge Orchestrator: $BRIDGE_ID"
echo ""

if [ -n "$WSL_IP" ]; then
    echo "WSL IP: $WSL_IP"
    echo "Mobile app should connect to: http://$WSL_IP:4943"
    echo ""
fi

echo "Next steps:"
echo "  1. Restart Metro bundler: cd Mobile && npm start --clear"
echo "  2. Test canisters: ./test-flow.sh"
echo "  3. Verify Mobile app can connect to canisters"
echo ""

if [ $VALIDATION_ERRORS -eq 0 ]; then
    echo -e "${GREEN}✓ All validations passed${NC}"
    exit 0
else
    echo -e "${YELLOW}⚠ Some validations failed. Please review above.${NC}"
    exit 1
fi

